server.port=8084

spring.application.name=customer-service

# --- Eureka (affichage instance) ---
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}



# --- H2 (pour dev / local) ---
spring.datasource.url=jdbc:h2:file:./data/customer/customerdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=cu
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.h2.console.enabled=true
# Console web H2 : http://localhost:8084/h2-console

# RabbitMQ
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms

banking.events.exchange=banking.events
banking.events.routing.documentSubmitted=document.submitted
banking.events.routing.documentProcessed=document.processed

