server.port=8086

spring.application.name=loan-service

# --- Eureka (affichage instance) ---
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}



# --- H2 (pour dev / local) ---
spring.datasource.url=jdbc:h2:mem:loandb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=lo
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
# Console web H2 : http://localhost:8086/h2-console

banking.events.exchange=banking.events
banking.events.routing.loanApproved=loan.approved
banking.events.routing.loanRejected=loan.rejected
banking.events.routing.documentProcessed=document.processed


