server.port=8086

spring.application.name=loan-service

spring.datasource.url=jdbc:postgresql://localhost:5432/loandb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

banking.events.exchange=banking.events
banking.events.routing.loanApproved=loan.approved
banking.events.routing.loanRejected=loan.rejected
banking.events.routing.documentProcessed=document.processed

