server.port=8082

spring.application.name=operator-service

# --- Eureka (affichage instance / éviter le hostname machine) ---
eureka.instance.hostname=localhost
# ID stable et lisible dans Eureka
# (permet d’éviter que “TAFEMPA” apparaisse comme host)
eureka.instance.instance-id=${spring.application.name}:${server.port}


# --- H2 (pour dev / local) ---
spring.datasource.url=jdbc:h2:mem:operatordb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=op
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
# Console web H2 : http://localhost:8082/h2-console

