server.port=8085

spring.application.name=transaction-service

# --- Eureka (affichage instance) ---
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}



# spring.application.name=loan-service

# --- H2 (pour dev / local) ---
spring.datasource.url=jdbc:h2:mem:transdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=tr
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
# Console web H2 : http://localhost:8085/h2-console

# Resilience4j circuitbreaker
resilience4j.circuitbreaker.instances.accountService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.accountService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.accountService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.accountService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.accountService.failureRateThreshold=50

resilience4j.circuitbreaker.instances.operatorService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.operatorService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.operatorService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.operatorService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.operatorService.failureRateThreshold=50

# Resilience4j retry
resilience4j.retry.instances.accountService.maxAttempts=3
resilience4j.retry.instances.accountService.waitDuration=1s
resilience4j.retry.instances.accountService.retryExceptions[0]=java.io.IOException
resilience4j.retry.instances.accountService.retryExceptions[1]=java.util.concurrent.TimeoutException

# RabbitMQ events
banking.events.exchange=banking.events
banking.events.routing.transactionCompleted=transaction.completed
banking.events.routing.transactionFailed=transaction.failed

