apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: finpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: finpay/audit-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9003
          env:
            - name: PORT
              value: "9003"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: RABBITMQ_EXCHANGE
              value: "banking.events"
            - name: DATA_DIR
              value: "/data/audit"
          volumeMounts:
            - name: audit-data
              mountPath: /data/audit
      volumes:
        - name: audit-data
          persistentVolumeClaim:
            claimName: audit-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: finpay
spec:
  selector:
    app: audit-service
  ports:
    - port: 9003
      targetPort: 9003
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-pvc
  namespace: finpay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
