# Minimal API Gateway config (the full routes/CORS/JWT are typically provided by the Config Server)

spring.application.name=api-gateway
spring.config.import=optional:configserver:http://localhost:8888

# spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.fail-fast=true

spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.retry.multiplier=1.1

# Force Eureka instance metadata for local dev
# (ensures the instance shows as localhost:<service>:<port>)
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}



